### ISSUE TITLE
对于多核心CPU使用率显示不正确

### ISSUE THREAD

**Issue by Edwin-Van** [188080501/JQCPUMonitor#4]
CPU使用率数值显示不正确

错误的显示：
CPU(Now): 0.00915903
CPU(Now): 0.0141549
CPU(Now): 0.00749376
CPU(Now): 0.0125
CPU(Now): 0.00582848
CPU(Now): 0.00999167
CPU(Now): 0.00999167

CPU

	Intel(R) Xeon(R) CPU E5-2675 v3 @ 1.80GHz

	基准速度:	1.80 GHz
	插槽:	1
	内核:	16
	逻辑处理器:	32
	虚拟化:	已启用
	L1 缓存:	1.0 MB
	L2 缓存:	4.0 MB
	L3 缓存:	40.0 MB

	利用率	3%
	速度	1.86 GHz
	正常运行时间	0:03:59:04
	进程	244
	线程	3801
	句柄	110477

**Comment by 188080501** [comment]
1. 请参考 https://github.com/188080501/JQCPUMonitor/issues/2
2. 请核对和资源管理器内CPU使用率是否一致
3. 请适当提高CPU使用率，比如说至20%，再查看差异是否还很大
