### ISSUE TITLE
代码中给出的Example运行编译失败

### ISSUE THREAD

**Issue by SiyerBOBO** [188080501/JQCPUMonitor#5]
编译环境MSVC 2019 x64、MinGW-64bit
如题，望作者百忙之中予以修复：
编译输出如下：
1>main.obj : error LNK2019: 无法解析的外部符号 "public: static void __cdecl JQCPUMonitor::initialize(void)" (?initialize@JQCPUMonitor@@SAXXZ)，函数 main 中引用了该符号
1>main.obj : error LNK2019: 无法解析的外部符号 "public: static double __cdecl JQCPUMonitor::cpuUsagePercentage(void)" (?cpuUsagePercentage@JQCPUMonitor@@SANXZ)，函数 main 中引用了该符号
1>main.obj : error LNK2019: 无法解析的外部符号 "public: static double __cdecl JQCPUMonitor::cpuUsagePercentageInTime(__int64 const &)" (?cpuUsagePercentageInTime@JQCPUMonitor@@SANAEB_J@Z)，函数 "public: static double __cdecl JQCPUMonitor::cpuUsagePercentageIn30Second(void)" (?cpuUsagePercentageIn30Second@JQCPUMonitor@@SANXZ) 中引用了该符号

**Comment by SiyerBOBO** [comment]
就算在QtCreater中依然报出同样的错误信息

**Comment by SiyerBOBO** [comment]
系统Windows 10 x64 2004

**Comment by 188080501** [comment]
默认工程编译不过去吗？

**Comment by 188080501** [comment]
这个感觉是你这边配置问题

**Comment by SiyerBOBO** [comment]
对滴   不是我配置问题吧QAQ   机器上其他项目都木有问题   Qt版本是5.15.0

**Comment by SiyerBOBO** [comment]
嗯好      我这边再检查一下  麻烦您也再次检查     关注你的这个项目好久了    首次遇到的时候就没编译过去

**Comment by SiyerBOBO** [comment]
作者您好  我这边已经找到了针对此问题的原因以及相关解决办法，具体如下：

根据编译器报错描述，意思Qt编译过程中没有元对象编译过程的参与，看了下该项目源码，发现了一个问题：

    在jqcpumonitor.inc文件中包含了inlin函数，但是这个.inc文件在编译器编译过程中并没有被元对象编译器发现（moc.exe)，于是我将jqcpumonitor.inc中的所有内容包含进jqcpumonitor.cpp文件的末尾位置，至此编译成功。

感谢作者对issue问题的关注与跟进。

**Comment by SiyerBOBO** [comment]
作者您好 我这边已经找到了针对此问题的原因以及相关解决办法，具体如下：

根据编译器报错描述，意思Qt编译过程中没有元对象编译过程的参与，看了下该项目源码，发现了一个问题：在jqcpumonitor.inc文件中包含了inlin函数，但是这个.inc文件在编译器编译过程中并没有被元对象编译器发现（moc.exe)，于是我将jqcpumonitor.inc中的所有内容包含进jqcpumonitor.h文件的末尾位置，至此编译成功。

感谢作者对issue问题的关注与跟进。
