### ISSUE TITLE
编译就过不了

### ISSUE THREAD

**Issue by Ansonjo** [188080501/JQCPUMonitor#7]
![image](https://user-images.githubusercontent.com/28035052/228107072-ff71872c-7e19-4eb0-aee2-79d5fb4cabd4.png)

**Comment by 188080501** [comment]
新版本的QtCreator可能无法识别pro中的*语法，导致cpp文件无法引入。
手动指定下文件名试试看

**Comment by 188080501** [comment]
已经进行修改，问题关闭
如果还有编译问题请说明下

**Comment by 188080501** [comment]
https://github.com/188080501/JQCPUMonitor/commit/6ace5ce6a66bd260ba0a1d850aaa6163e3fff5da
